### ISSUE TITLE
How to train the teacher model?

### ISSUE THREAD

**Issue by chenyingshu** [VITA-Group/INS#5]
Hi, thank you for the great work and sharing the code.
I now want to training other NeRF models for this work, and I can successfully run the sample training code with room+scream with given pre-trained checkpoint. 

But when I want to train other scenes or even train room scene from scratch, without any pre-trained checkpoint, I failed to get any reasonable results.
My config is just similar with "train_room_thescream_28G_mem.sh" expect that without ckpt_path.

In the paper, it also mention it needs train CIM only first, but I have no idea how to do it.
It sems to require "two-step" training,  please give some detailed instructions.

Hope to hear from you asap, thank you!

**Comment by chenyingshu** [comment]
Solved it.
In pure NeRF training stage, set STYLE_W=0, CONTENT_W=0, DENSITY_W=0, and only keep RGB_W=1, without teacher model.
In stylization training stage, train with previous pre-trained NeRF as teacher model, and set RGB_W=0.

**Comment by ipekoztas** [comment]
hi, how long did the training take?
